---
apiVersion: v1
kind: ConfigMap
metadata:
  name: metrics-configuration
  labels:
    app: fiufit
    tier: metrics-microservice
data:
  METRICS_DB_DATABASE: "fiufit"
  METRICS_DB_USER: "backend"
  METRICS_DB_PASSWORD: $USERS_DB_PASSWORD
  METRICS_DB_HOST: "dpg-cgno8m8rddl9mmvdaja0-a.oregon-postgres.render.com"
