---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: metrics
  labels:
    app: fiufit
    tier: metrics-microservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fiufit
      tier: metrics-microservice
  template:
    metadata:
      labels:
        app: fiufit
        tier: metrics-microservice
    spec:
      containers:
      - name: metrics
        image: marianocinalli/metrics:v0.0.1
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: metrics-configuration
        ports:
          - containerPort: 8005
            name: http-metrics
        resources:
          limits:
            memory: 512Mi
            cpu: "1"
          requests:
            memory: 128Mi
            cpu: "0.2"
