---
apiVersion: v1
kind: Service
metadata:
  name: metrics-service
  labels:
    app: fiufit
    tier: metrics-service
spec:
  type: ClusterIP
  ports:
  - name: metrics-svc
    protocol: TCP
    port: 8005
    targetPort: http-metrics
  selector:
    app: fiufit
    tier: metrics-microservice
